package squid

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/vt887/macnet-gateway/daemon/internal/services"
)

const configFileName = "00-main.conf"

var ErrInvalidConfig = errors.New("invalid squid config")

type MockService struct {
	generatedConfigDir string
}

func NewMockService(generatedConfigDir string) *MockService {
	return &MockService{generatedConfigDir: generatedConfigDir}
}

func (m *MockService) Status(_ context.Context) (services.ServiceStatus, error) {
	if _, err := exec.LookPath("squid"); err == nil {
		return services.ServiceStatus{Name: "squid", Status: "available", Message: "binary detected"}, nil
	}
	return services.ServiceStatus{Name: "squid", Status: "mock", Message: "binary not found; mock mode"}, nil
}

func (m *MockService) Settings(_ context.Context) (services.ProxySettings, error) {
	return services.ProxySettings{
		ListenAddress:       "127.0.0.1:3128",
		CacheDirectory:      "/Library/Caches/MacNetGateway/squid",
		GeneratedConfigPath: m.generatedConfigDir,
	}, nil
}

func (m *MockService) ConfigPreview(_ context.Context) (string, error) {
	content, err := os.ReadFile(filepath.Join(m.generatedConfigDir, "conf.d", configFileName))
	if err != nil {
		return "", err
	}
	return string(content), nil
}

func (m *MockService) RenderConfig(_ context.Context) error {
	confDir := filepath.Join(m.generatedConfigDir, "conf.d")
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}

	config := strings.TrimSpace(`
# Generated by MacNet Gateway (PR-3 mock skeleton)
http_port 127.0.0.1:3128
cache_dir ufs /Library/Caches/MacNetGateway/squid 4096 16 256
access_log stdio:/Library/Application Support/MacNetGateway/logs/access.log
`)
	return os.WriteFile(filepath.Join(confDir, configFileName), []byte(config+"\n"), 0o644)
}

func (m *MockService) ValidateConfig(ctx context.Context) error {
	preview, err := m.ConfigPreview(ctx)
	if err != nil {
		return err
	}
	if !strings.Contains(preview, "http_port") {
		return errors.Join(ErrInvalidConfig, errors.New("generated squid config is missing http_port"))
	}
	return nil
}

func (m *MockService) Reload(_ context.Context) error  { return nil }
func (m *MockService) Start(_ context.Context) error   { return nil }
func (m *MockService) Stop(_ context.Context) error    { return nil }
func (m *MockService) Restart(_ context.Context) error { return nil }

func (m *MockService) TailAccessLog(_ context.Context) (<-chan services.ProxyEvent, error) {
	ch := make(chan services.ProxyEvent)
	close(ch)
	return ch, nil
}
