package dns

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/vt887/macnet-gateway/daemon/internal/services"
)

const configFileName = "00-main.conf"

var ErrInvalidConfig = errors.New("invalid dns config")

type MockService struct {
	generatedConfigDir string
}

func NewMockService(generatedConfigDir string) *MockService {
	return &MockService{generatedConfigDir: generatedConfigDir}
}

func (m *MockService) Status(_ context.Context) (services.ServiceStatus, error) {
	if _, err := exec.LookPath("dnsmasq"); err == nil {
		return services.ServiceStatus{Name: "dns", Status: "available", Message: "dnsmasq binary detected"}, nil
	}
	return services.ServiceStatus{Name: "dns", Status: "mock", Message: "dns engine binary not found; mock mode"}, nil
}

func (m *MockService) Settings(_ context.Context) (services.DNSSettings, error) {
	return services.DNSSettings{
		ListenAddress:       "127.0.0.1:53",
		UpstreamMode:        "doh",
		Provider:            "cloudflare",
		GeneratedConfigPath: m.generatedConfigDir,
	}, nil
}

func (m *MockService) ConfigPreview(_ context.Context) (string, error) {
	content, err := os.ReadFile(filepath.Join(m.generatedConfigDir, "conf.d", configFileName))
	if err != nil {
		return "", err
	}
	return string(content), nil
}

func (m *MockService) RenderConfig(_ context.Context) error {
	confDir := filepath.Join(m.generatedConfigDir, "conf.d")
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}

	config := strings.TrimSpace(`
# Generated by MacNet Gateway (PR-4 mock skeleton)
listen-address=127.0.0.1
port=53
server=1.1.1.1
cache-size=1000
`)
	return os.WriteFile(filepath.Join(confDir, configFileName), []byte(config+"\n"), 0o644)
}

func (m *MockService) ValidateConfig(ctx context.Context) error {
	preview, err := m.ConfigPreview(ctx)
	if err != nil {
		return err
	}
	if !strings.Contains(preview, "listen-address") {
		return errors.Join(ErrInvalidConfig, errors.New("generated dns config is missing listen-address"))
	}
	return nil
}

func (m *MockService) Reload(_ context.Context) error  { return nil }
func (m *MockService) Start(_ context.Context) error   { return nil }
func (m *MockService) Stop(_ context.Context) error    { return nil }
func (m *MockService) Restart(_ context.Context) error { return nil }

func (m *MockService) TailQueryLog(_ context.Context) (<-chan services.DNSEvent, error) {
	ch := make(chan services.DNSEvent)
	close(ch)
	return ch, nil
}
